apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-tower-job-app
  namespace: mike-ansible
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - demo-tower-job-app
