apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ansible-tower-job-app
  namespace: default
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - ansible-tower-job-app
