apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ansible-tower-job-app-subscription
  namespace: default
  labels:
    app: ansible-tower-job-app
  annotations:
    apps.open-cluster-management.io/github-path: ansible-job-op
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: ansible-tower-job-ch/ansible-tower-job-channel
  placement:
    local: true
